### ISSUE TITLE
Port Finder logic doesn't reliably return an unused port :(

### ISSUE THREAD

**Issue by wdschei** [rackerlabs/deproxy#52]
On my local box I kept getting Bind exceptions when trying to use deproxy testing Repose.

Adding 10 to the port number returned made the exception go away. 

This is probably not easy to reproduce.... Basically, the port finding logic isn't sound enough to reliably return unused ports.

**Comment by dkowis** [comment]
Relates to #63. if I can invert the port logic, I could maybe solve this problem.
